name: dbt CI

on:
  pull_request:
    branches: [main]

jobs:
  dbt-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dbt
        run: pip install dbt-snowflake==1.11.5

      - name: Install dbt packages
        working-directory: smart_grid_dbt
        run: dbt deps

      - name: dbt compile (validates SQL without DB connection)
        working-directory: smart_grid_dbt
        run: dbt compile
